image: alpine/latest
packages:
  - docker
secrets:
  - a1b281aa-40e6-49d8-9dfc-39240ac3f027
sources:
  - https://git.sr.ht/~patrickhaussmann/dotfiles
tasks:
- setup: |
    sudo addgroup ${USER} docker
    sudo service docker start
    sleep 10

- login: |
    cat ~/.docker-hub-personal-access-token | docker login --username patrickhaussmann --password-stdin

- build: |
    cd dotfiles/.builds
    docker build -f Dockerfile . -t dev

- publish: |
    docker tag dev patrickhaussmann/dev
    docker push patrickhaussmann/dev
