#!/bin/bash
set -euf -o pipefail

if [ $# -eq 0 ] || [ "$1" = "-h" ] ; then
    echo -e "Usage:\n$(basename $BASH_SOURCE) TOPIC       show cheat sheet on the TOPIC\n$(basename $BASH_SOURCE) TOPIC/SUB   show cheat sheet on the SUB topic in TOPIC\n$(basename $BASH_SOURCE) ~KEYWORD    search cheat sheets for KEYWORD"
    exit 0
fi

curl "https://cheat.sh/$*"
