#!/bin/bash
set -e


set +e
# check if docker is installed
which docker >/dev/null 2>&1
if [[ $? != 0 ]]; then
	echo docker not installed!!
	exit 1
fi

# check if network exists
docker network inspect dev_net >/dev/null 2>&1
if [[ $? != 0 ]]; then
	docker network create dev_net --subnet=10.11.0.0/16
fi
set -e


# stop and delete container -> restart
if [[ $1 == "-r" ]]; then
	docker rm -f dev
fi


# ensure container is running
if [ ! "$(docker ps -q -f name=dev)" ]; then
    # run container
	docker run -it -d --name dev -h dev --net dev_net --ip 10.11.0.10 -v /home/$USER/.ssh:/home/patrick/.ssh:ro -v /home/$USER:/host patrickhaussmann/dev
fi

# set working dir to pwd
if [[ $1 == "-d" ]]; then
	if [[ $PWD/ = /home/$USER/* ]]; then
		docker exec -it -w $(pwd | sed "s/home\/$USER/host/g") dev bash
		exit 0
	fi
fi


docker exec -it dev bash
#docker attach --sig-proxy=false dev
