#!/bin/bash
set -eu

if [ "$#" -ne 2 ]; then
    echo "please supply two files to diff"
else
  hash1=$(md5sum "${1}" | cut -d' ' -f1)
  hash2=$(md5sum "${2}" | cut -d' ' -f1)

  if [ "$hash1" == "$hash2" ]; then
    echo "identical"
  else
    echo "different"
  fi
fi

