#!/bin/bash
set -euf -o pipefail
set +u

if [ "$1" = "-h" ] ; then
    echo "Usage:\n $(basename $BASH_SOURCE) <?length>"
    exit 0
fi

_passwordblock() {
  tr -cd '[:alpha:]' < /dev/urandom | tr -d 'Il' | head -c3
  tr -cd '[:digit:]' < /dev/urandom | head -c1
}

password() {
  _passwordblock
  i=1
  while [ $i -lt $length ]
  do
    printf "-"
    _passwordblock
    i=$((i+1))
  done
}

length=8

if [ ! -z "$1" ]; then
  length="$1"
fi

echo "$(password)"
