#!/bin/sh
set -e

if [ "$1" = "-h" ] ; then
    echo "Usage:\n $0 <?length> <?rows>"
    exit 0
fi

_passwordblock() {
  tr -cd '[:alpha:]' < /dev/urandom | tr -d 'Il' | head -c3
  tr -cd '[:digit:]' < /dev/urandom | head -c1
}

password() {
  _passwordblock
  i=1
  while [ $i -lt $length ]
  do
    printf "-"
    _passwordblock
    i=$((i+1))
  done
}

length=8
rows=20

if [ ! -z "$1" ]; then
  length="$1"
fi

if [ ! -z "$2" ]; then
  rows="$2"
fi

i=0
while [ $i -lt $rows ]
do
  printf "%2d: %s\n" "$((i+1))" "$(password)"
  i=$((i+1))
done

