#!/bin/bash
set -ef -o pipefail

if [ "$1" = "-h" ] ; then
    echo "Usage:\n $(basename $BASH_SOURCE) <file|text>\n ... | $(basename $BASH_SOURCE)"
    exit 0
fi

if [ $# -eq 0 ] ; then
    # read content from stdin
    cat | curl -F 'f:1=<-' ix.io
else
    if [ -f $1 ] || [ -h $1 ] ; then
        # use content of the file/symlink in first argument
        cat $1 | curl -F 'f:1=<-' ix.io
    else
        # use arguments as content
        echo $* | curl -F 'f:1=<-' ix.io
    fi
fi
