#!/bin/bash
set -ef -o pipefail

if [ "$1" = "-h" ] ; then
    echo "Usage:\n $(basename $BASH_SOURCE) <url>\n ... | $(basename $BASH_SOURCE)"
    exit 0
fi

if [ $# -eq 0 ] ; then
    # read url from stdin
    cat | curl -F-=\<- qrenco.de
else
    # use arguments as input
    echo $* | curl -F-=\<- qrenco.de
fi
