#!/bin/bash
set -euf -o pipefail

if [ $# -ne 1 ] || [ "$1" = "-h" ] ; then
    echo "Usage:\n $(basename $BASH_SOURCE) <long url>"
    exit 0
fi

curl "https://is.gd/create.php?format=simple&url=$(echo $1 | jq -Rr @uri)"
