#!/bin/bash
set -euf -o pipefail

if [ $# -lt 2 ] || [ $# -gt 3 ] || [ "$1" = "-h" ] ; then
    echo "Incremental backups using rsync and hardlinks\n\nUsage:\n $(basename $BASH_SOURCE) [OPTIONS] <source folder> <snapshot folder>\n\n -c: stop after copy\n -r: resume even if folder \"CURRENT\" is found"
    exit 0
fi

OPTIONS=""
if [ $# -eq 3 ] ; then
  OPTIONS="$1"
  shift
fi

SOURCE_DIR="$1"
SNAPSHOT_DIR="$2"
LATEST="${SNAPSHOT_DIR}/latest"
CURRENT="${SNAPSHOT_DIR}/current"
EXCLUDE="${SNAPSHOT_DIR}/exclude.txt"


if [ ! -d "${SOURCE_DIR}" ] || [ ! -d "${SNAPSHOT_DIR}" ] ; then
  echo "Directory does not exist"
  exit 1
fi

if [ ! -n "$(ls -A "${SOURCE_DIR}")" ]; then
   echo "Source is empty"
   exit 1
fi

if [ "${SOURCE_DIR}" = "${SNAPSHOT_DIR}" ] ; then
  echo "Source and snapshot folders are the same"
  exit 1
fi

if ! ( [ -h "${LATEST}" ] || [ -d "${LATEST}" ] ) ; then
  mkdir "${LATEST}"
fi

if ( [ -h "${CURRENT}" ] || [ -d "${CURRENT}" ] ) && [ "${OPTIONS}" != "-r" ] ; then
  echo 'Folder "CURRENT" does already exist\nUse Option "-r" to resume anyway'
  exit 1
fi

cp -lRu "${LATEST}" "${CURRENT}"
rm -rf "${LATEST}"

if [ ! -f "${EXCLUDE}" ] ; then
  touch "${EXCLUDE}"
fi

if [ "${OPTIONS}" = "-c" ] ; then
  echo 'Exit after copy'
  exit 0
fi

rsync -ahv --info=progress2 --stats --delete "${SOURCE_DIR}" "${CURRENT}" --exclude-from="${EXCLUDE}"

DATETIME="$(date -u +%FT%T%Z)"
BACKUP_PATH="${SNAPSHOT_DIR}/${DATETIME}"

mv "${CURRENT}" "${BACKUP_PATH}"

ln -s "${DATETIME}" "${LATEST}"
