#!/bin/sh

if [ $# -eq 0 ] || [ "$1" = "-h" ] ; then
    echo "Usage:\n $0 <file>\n ... | $0 <file_name>"
    exit 0
fi

if [ -z $1 ] ; then
    echo "No arguments specified" >&2
    exit 1
fi

if [ -f "$1" ] || [ -h "$1" ] ; then
    file_name=$(basename "$1")
    cat "$1" | curl --progress-bar --upload-file "-" "http://transfer.sh/$file_name" | tee /dev/null
else
    file_name=$1
    cat | curl --progress-bar --upload-file "-" "http://transfer.sh/$file_name" | tee /dev/null
fi

