#!/bin/bash
set -ef -o pipefail

if [ "$1" = "-h" ] ; then
    echo "Usage:\n $(basename $BASH_SOURCE) <?number of blocks>"
    exit 0
fi

_usernameblock() {
  tr -cd 'bcdfghjklmnpqrstvwxyz' < /dev/urandom | head -c1
  tr -cd 'aeiou' < /dev/urandom | head -c1
}

username() {
  i=1
  while [ $i -lt $length ]
  do
    _usernameblock
    i=$((i+1))
  done
}

length=5

if [ ! -z "$1" ]; then
  length="$1"
fi

echo "$(username)"
