# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.hostname = "vagrant-kali"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |v|
    v.name = "kali-vagrant"
    v.cpus = 2
    v.memory = 1024
    v.gui = true
  end

  config.vm.provision "shell", inline: <<-SHELL
	sudo apt-get update && sudo apt-get upgrade -y
SHELL
end
